-- AlterTable
ALTER TABLE `users` ADD COLUMN `approvedAt` DATETIME(3) NULL,
    ADD COLUMN `name` VARCHAR(191) NULL,
    ADD COLUMN `role` ENUM('MEMBER', 'STAFF', 'ADMIN') NOT NULL DEFAULT 'MEMBER',
    ADD COLUMN `status` ENUM('PENDING', 'APPROVED') NOT NULL DEFAULT 'PENDING';
